'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';import {useRouter} from 'next/navigation';import {createClient} from '@/lib/supabase/client';import {generateCandidates} from '@/lib/supabase/questionFactory';
type Q={id:string;question:string;choices:string[];category:string;status:string;featured:boolean};
export default function Machine(){const s=createClient(),r=useRouter();const [items,setItems]=useState<Q[]>([]),[msg,setMsg]=useState(''),[working,setWorking]=useState(false);
async function load(){const {data:{user}}=await s.auth.getUser();if(!user){r.replace('/auth?mode=signin');return}const {data,error}=await s.rpc('get_pick_machine_queue',{p_limit:100});if(error)return setMsg(error.message);setItems((data||[]) as Q[])}useEffect(()=>{load()},[]);
async function generate(){setWorking(true);const existing=new Set(items.map(x=>x.question));const batch=generateCandidates(12).filter(x=>!existing.has(x.question));let n=0;for(const x of batch){const {error}=await s.rpc('admin_add_machine_pick',{p_question:x.question,p_choices:x.choices,p_category:x.category,p_featured:false,p_expires_minutes:x.expiresMinutes});if(!error)n++}setMsg(`Generated ${n} candidates for review.`);setWorking(false);load()}
async function act(id:string,type:'publish'|'reject'){const {error}=await s.rpc(type==='publish'?'admin_publish_machine_pick':'admin_reject_machine_pick',{p_queue_id:id});setMsg(error?error.message:type==='publish'?'Approved and published.':'Candidate denied.');load()}
const drafts=items.filter(x=>x.status==='draft');
return <main className="adminShell"><div className="adminTitle"><div><p className="feedEyebrow">QUESTION FACTORY</p><h1>PICK Machine</h1><p className="muted">Generate a surprise pool. Nothing reaches the feed until you approve it.</p></div><div className="row"><button className="primary" disabled={working} onClick={generate}>{working?'Generating…':'Generate 12 candidates'}</button><Link className="secondary" href="/admin">← Admin</Link></div></div>{msg&&<div className="machineNotice">{msg}</div>}<section className="adminPanel"><div className="feedHeader"><div><p className="feedEyebrow">ADMIN REVIEW</p><h2>Candidate pool</h2></div><button className="secondary" onClick={load}>Refresh</button></div>{!drafts.length&&<p className="muted">No candidates waiting. Generate a batch.</p>}{drafts.map(x=><article className="machineItem" key={x.id}><div className="row"><span className="statusPill">{x.category}</span></div><h3>{x.question}</h3><p className="muted">{x.choices.join(' • ')}</p><div className="row"><button className="primary" onClick={()=>act(x.id,'publish')}>Approve & publish</button><button className="secondary" onClick={()=>act(x.id,'reject')}>Deny</button></div></article>)}</section></main>}
