'use client';
import {FormEvent,useEffect,useState} from 'react';import Link from 'next/link';import {useRouter} from 'next/navigation';import {createClient} from '@/lib/supabase/client';
type Q={id:string;question:string;choices:string[];category:string;status:string;featured:boolean;expires_minutes:number|null;published_pick_id:string|null};
const cats=['Everyday','Food','Dating','Entertainment','Style','Money','Travel','Tech','Hypothetical'];
export default function Machine(){const s=createClient(),r=useRouter();const [items,setItems]=useState<Q[]>([]),[q,setQ]=useState(''),[choices,setChoices]=useState(['','']),[cat,setCat]=useState('Everyday'),[featured,setFeatured]=useState(false),[expiry,setExpiry]=useState('1440'),[msg,setMsg]=useState('');
async function load(){const {data:{user}}=await s.auth.getUser();if(!user){r.replace('/auth?mode=signin');return}const {data,error}=await s.rpc('get_pick_machine_queue',{p_limit:100});if(error){setMsg(error.message);return}setItems((data||[]) as Q[])}useEffect(()=>{load()},[]);
async function add(e:FormEvent){e.preventDefault();const c=choices.map(x=>x.trim()).filter(Boolean);if(c.length<2)return setMsg('Add at least two choices.');const {error}=await s.rpc('admin_add_machine_pick',{p_question:q.trim(),p_choices:c,p_category:cat,p_featured:featured,p_expires_minutes:Number(expiry)});if(error)return setMsg(error.message);setQ('');setChoices(['','']);setFeatured(false);setMsg('Added to machine queue.');load()}
async function action(id:string,type:'publish'|'reject'){setMsg('Working…');const {error}=await s.rpc(type==='publish'?'admin_publish_machine_pick':'admin_reject_machine_pick',{p_queue_id:id});setMsg(error?error.message:type==='publish'?'Published to public feed.':'Rejected.');load()}
return <main className="adminShell"><div className="adminTitle"><div><p className="feedEyebrow">CONTENT ENGINE</p><h1>PICK Machine</h1><p className="muted">Build the queue, review it, then publish system PICKs into the public feed.</p></div><Link className="secondary" href="/admin">← Admin</Link></div>
<section className="machineGrid"><form className="adminPanel machineComposer" onSubmit={add}><h2>Create candidate</h2><textarea className="field" required maxLength={280} value={q} onChange={e=>setQ(e.target.value)} placeholder="What should the crowd PICK?"/>{choices.map((x,i)=><input className="field" key={i} required={i<2} value={x} onChange={e=>{let n=[...choices];n[i]=e.target.value;setChoices(n)}} placeholder={'Choice '+(i+1)}/>)}{choices.length<4&&<button type="button" className="secondary" onClick={()=>setChoices([...choices,''])}>+ Choice</button>}<select className="field" value={cat} onChange={e=>setCat(e.target.value)}>{cats.map(x=><option key={x}>{x}</option>)}</select><select className="field" value={expiry} onChange={e=>setExpiry(e.target.value)}><option value="60">1 hour</option><option value="360">6 hours</option><option value="1440">24 hours</option><option value="4320">3 days</option><option value="0">No expiration</option></select><label className="browseToggle"><input type="checkbox" checked={featured} onChange={e=>setFeatured(e.target.checked)}/><span><b>Feature when published</b><small>Give this PICK priority in the public feed.</small></span></label><button className="primary">Add to queue</button>{msg&&<p className="muted">{msg}</p>}</form>
<section className="adminPanel"><div className="feedHeader"><div><p className="feedEyebrow">QUEUE</p><h2>Machine PICKs</h2></div><button className="secondary" onClick={load}>Refresh</button></div>{!items.length&&<p className="muted">Queue is empty. Create the first system PICK.</p>}{items.map(x=><article className="machineItem" key={x.id}><div className="row"><span className="statusPill">{x.category}</span><span className={'statusPill '+(x.status==='published'?'live':'')}>{x.status.toUpperCase()}</span>{x.featured&&<span className="statusPill featured">FEATURED</span>}</div><h3>{x.question}</h3><p className="muted">{x.choices.join(' • ')}</p>{x.status==='draft'&&<div className="row"><button className="primary" onClick={()=>action(x.id,'publish')}>Publish</button><button className="secondary" onClick={()=>action(x.id,'reject')}>Reject</button></div>}</article>)}</section></section></main>}
