'use client';
import {useEffect,useMemo,useState} from 'react';import Link from 'next/link';import {createClient} from '@/lib/supabase/client';
type Pick={id:string;slug:string;question:string;is_featured:boolean};type Choice={id:string;label:string;position:number};type Result={choice_id:string;vote_count:number;total_votes:number};
const key='pick-player-seen-v1';
function token(){let t=localStorage.getItem('pick-voter-token');if(!t){t=crypto.randomUUID()+crypto.randomUUID();localStorage.setItem('pick-voter-token',t)}return t}
function seen(){try{return JSON.parse(localStorage.getItem(key)||'[]') as string[]}catch{return[]}}
function remember(id:string){const a=seen();if(!a.includes(id))localStorage.setItem(key,JSON.stringify([...a,id].slice(-250)))}
export default function PublicFeed(){const s=useMemo(()=>createClient(),[]);const [pool,setPool]=useState<Pick[]>([]),[i,setI]=useState(0),[choices,setChoices]=useState<Choice[]>([]),[results,setResults]=useState<Result[]|null>(null),[busy,setBusy]=useState(true),[done,setDone]=useState(false);
async function load(){setBusy(true);const {data}=await s.rpc('get_public_pick_feed',{p_limit:50});const all=(data||[]) as Pick[];let p=all.filter(x=>!seen().includes(x.id)).sort(()=>Math.random()-.5);if(!p.length&&all.length){localStorage.removeItem(key);p=[...all].sort(()=>Math.random()-.5)}setPool(p);setI(0);setDone(!p.length);setBusy(false)}
useEffect(()=>{load()},[]);const current=pool[i];
useEffect(()=>{if(!current)return;setResults(null);setChoices([]);setBusy(true);(async()=>{const {data:c}=await s.from('pick_choices').select('id,label,position').eq('pick_id',current.id).order('position');setChoices(c||[]);const {data:r}=await s.rpc('get_anonymous_pick_results',{p_pick_id:current.id,p_voter_token:token()});if(r?.length)setResults(r as Result[]);setBusy(false)})()},[current?.id]);
function next(){if(current)remember(current.id);if(i+1>=pool.length){setDone(true);return}setI(x=>x+1)}
async function vote(id:string){if(!current)return;setBusy(true);await s.rpc('cast_anonymous_vote',{p_pick_id:current.id,p_choice_id:id,p_voter_token:token()});const {data:r}=await s.rpc('get_anonymous_pick_results',{p_pick_id:current.id,p_voter_token:token()});if(r?.length)setResults(r as Result[]);remember(current.id);setBusy(false)}
if(busy&&!current)return <div className="playerCard"><p className="muted">Finding your next PICK…</p></div>;
if(done||!current)return <div className="playerCard playerDone"><p className="feedEyebrow">YOU CLEARED THE DECK</p><h2>You've seen the current PICK pool.</h2><p className="muted">Come back for fresh decisions—or make one.</p><div className="row"><button className="secondary" onClick={()=>{setDone(false);load()}}>Shuffle again</button><Link className="primary" href="/create">Create a PICK</Link></div></div>;
const total=results?.[0]?.total_votes||0;
return <div className="pickPlayer"><div className="playerTop"><span className="feedEyebrow">PICK {i+1} · SURPRISE ME</span><span className="muted">{pool.length-i} in deck</span></div><article className="playerCard">{current.is_featured&&<span className="feedBadge">FEATURED</span>}<h2>{current.question}</h2>{results?choices.map(c=>{const n=results.find(x=>x.choice_id===c.id)?.vote_count||0,p=total?Math.round(n/total*100):0;return <div className="result" key={c.id}><div className="row between"><b>{c.label}</b><b>{p}%</b></div><div className="bar"><div className="fill" style={{width:p+'%'}}/></div></div>}):choices.map(c=><button className="choice playerChoice" disabled={busy} onClick={()=>vote(c.id)} key={c.id}>{c.label}</button>)}<div className="playerFooter">{results?<><span className="muted">{total} vote{total===1?'':'s'} · Crowd unlocked</span><button className="primary" onClick={next}>Next PICK →</button></>:<><button className="skipButton" disabled={busy} onClick={next}>Skip →</button><span className="muted">Pick first. See the crowd second.</span></>}</div><Link className="feedLink" href={'/p/'+current.slug}>Open & share</Link></article></div>}
